# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  # Push to Docker Hub
  docker:
    runs-on: ubuntu-latest

    needs: [build]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest

  # Push to Vercel
  vercel:
    runs-on: ubuntu-latest
    
    needs: [build]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Vercel Action
        uses: amondnet/vercel-action@v20 #deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
            vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
            vercel-args: '--prod' #Optional
            github-token: ${{ secrets.PAT }} #Optional 
            #working-directory: ./sub-directory
